//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Док смета.
    /// </summary>
    // *** Start programmer edit section *** (ДокСмета CustomAttributes)

    // *** End programmer edit section *** (ДокСмета CustomAttributes)
    [AutoAltered()]
    [Caption("Документ смета")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокСметаE", new string[] {
            "НомСметРасч as \'Номер сметных расчетов\'",
            "Количество as \'Количество\'",
            "ЦенаЗаЕд as \'Цена за единицу\'",
            "ОбРабПоСмет as \'Объем работ по смете\'",
            "ОбщСметСтои as \'Общая сметная стоимость\'",
            "ОбъектСМР as \'Объект строительства\'",
            "ОбъектСМР.ОбъектСтроит as \'Объект строительства\'",
            "Номенклатура as \'Номенклатура\'",
            "Номенклатура.Наименов as \'Номенклатура\'",
            "СпрКонтраг as \'Контрагент\'",
            "СпрКонтраг.Наименование as \'Контрагент\'",
            "ЕдИзмерен as \'Единицы измерения\'",
            "ЕдИзмерен.Наименование as \'Единицы измерения\'"})]
    [AssociatedDetailViewAttribute("ДокСметаE", "ТЧСмета", "ТЧСметаE", true, "", "Табличная часть сметы", true, new string[] {
            ""})]
    [View("ДокСметаL", new string[] {
            "НомСметРасч as \'Номер сметных расчетов\'",
            "Количество as \'Количество\'",
            "ЦенаЗаЕд as \'Цена за единицу\'",
            "ОбРабПоСмет as \'Объем работ по смете\'",
            "ОбщСметСтои as \'Общая сметная стоимость\'",
            "ОбъектСМР.ОбъектСтроит as \'Объект строительства\'",
            "Номенклатура.Наименов as \'Номенклатура\'",
            "СпрКонтраг.Наименование as \'Контрагент\'",
            "ЕдИзмерен.Наименование as \'Единицы измерения\'"})]
    public class ДокСмета : ICSSoft.STORMNET.DataObject
    {
        
        private float fЦенаЗаЕд;
        
        private float fОбщСметСтои;
        
        private int fКоличество;
        
        private int fНомСметРасч;
        
        private float fОбРабПоСмет;
        
        private IIS.Proekt.ЕдИзмерен fЕдИзмерен;
        
        private IIS.Proekt.ОбъектСМР fОбъектСМР;
        
        private IIS.Proekt.СпрКонтраг fСпрКонтраг;
        
        private IIS.Proekt.Номенклатура fНоменклатура;
        
        private IIS.Proekt.DetailArrayOfТЧСмета fТЧСмета;
        
        // *** Start programmer edit section *** (ДокСмета CustomMembers)

        // *** End programmer edit section *** (ДокСмета CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ДокСмета.Количество CustomAttributes)

        // *** End programmer edit section *** (ДокСмета.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ДокСмета.Количество Get start)

                // *** End programmer edit section *** (ДокСмета.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ДокСмета.Количество Get end)

                // *** End programmer edit section *** (ДокСмета.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокСмета.Количество Set start)

                // *** End programmer edit section *** (ДокСмета.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ДокСмета.Количество Set end)

                // *** End programmer edit section *** (ДокСмета.Количество Set end)
            }
        }
        
        /// <summary>
        /// НомСметРасч.
        /// </summary>
        // *** Start programmer edit section *** (ДокСмета.НомСметРасч CustomAttributes)

        // *** End programmer edit section *** (ДокСмета.НомСметРасч CustomAttributes)
        public virtual int НомСметРасч
        {
            get
            {
                // *** Start programmer edit section *** (ДокСмета.НомСметРасч Get start)

                // *** End programmer edit section *** (ДокСмета.НомСметРасч Get start)
                int result = this.fНомСметРасч;
                // *** Start programmer edit section *** (ДокСмета.НомСметРасч Get end)

                // *** End programmer edit section *** (ДокСмета.НомСметРасч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокСмета.НомСметРасч Set start)

                // *** End programmer edit section *** (ДокСмета.НомСметРасч Set start)
                this.fНомСметРасч = value;
                // *** Start programmer edit section *** (ДокСмета.НомСметРасч Set end)

                // *** End programmer edit section *** (ДокСмета.НомСметРасч Set end)
            }
        }
        
        /// <summary>
        /// ОбРабПоСмет.
        /// </summary>
        // *** Start programmer edit section *** (ДокСмета.ОбРабПоСмет CustomAttributes)

        // *** End programmer edit section *** (ДокСмета.ОбРабПоСмет CustomAttributes)
        public virtual float ОбРабПоСмет
        {
            get
            {
                // *** Start programmer edit section *** (ДокСмета.ОбРабПоСмет Get start)

                // *** End programmer edit section *** (ДокСмета.ОбРабПоСмет Get start)
                float result = this.fОбРабПоСмет;
                // *** Start programmer edit section *** (ДокСмета.ОбРабПоСмет Get end)

                // *** End programmer edit section *** (ДокСмета.ОбРабПоСмет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокСмета.ОбРабПоСмет Set start)

                // *** End programmer edit section *** (ДокСмета.ОбРабПоСмет Set start)
                this.fОбРабПоСмет = value;
                // *** Start programmer edit section *** (ДокСмета.ОбРабПоСмет Set end)

                // *** End programmer edit section *** (ДокСмета.ОбРабПоСмет Set end)
            }
        }
        
        /// <summary>
        /// ОбщСметСтои.
        /// </summary>
        // *** Start programmer edit section *** (ДокСмета.ОбщСметСтои CustomAttributes)

        // *** End programmer edit section *** (ДокСмета.ОбщСметСтои CustomAttributes)
        public virtual float ОбщСметСтои
        {
            get
            {
                // *** Start programmer edit section *** (ДокСмета.ОбщСметСтои Get start)

                // *** End programmer edit section *** (ДокСмета.ОбщСметСтои Get start)
                float result = this.fОбщСметСтои;
                // *** Start programmer edit section *** (ДокСмета.ОбщСметСтои Get end)

                // *** End programmer edit section *** (ДокСмета.ОбщСметСтои Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокСмета.ОбщСметСтои Set start)

                // *** End programmer edit section *** (ДокСмета.ОбщСметСтои Set start)
                this.fОбщСметСтои = value;
                // *** Start programmer edit section *** (ДокСмета.ОбщСметСтои Set end)

                // *** End programmer edit section *** (ДокСмета.ОбщСметСтои Set end)
            }
        }
        
        /// <summary>
        /// ЦенаЗаЕд.
        /// </summary>
        // *** Start programmer edit section *** (ДокСмета.ЦенаЗаЕд CustomAttributes)

        // *** End programmer edit section *** (ДокСмета.ЦенаЗаЕд CustomAttributes)
        public virtual float ЦенаЗаЕд
        {
            get
            {
                // *** Start programmer edit section *** (ДокСмета.ЦенаЗаЕд Get start)

                // *** End programmer edit section *** (ДокСмета.ЦенаЗаЕд Get start)
                float result = this.fЦенаЗаЕд;
                // *** Start programmer edit section *** (ДокСмета.ЦенаЗаЕд Get end)

                // *** End programmer edit section *** (ДокСмета.ЦенаЗаЕд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокСмета.ЦенаЗаЕд Set start)

                // *** End programmer edit section *** (ДокСмета.ЦенаЗаЕд Set start)
                this.fЦенаЗаЕд = value;
                // *** Start programmer edit section *** (ДокСмета.ЦенаЗаЕд Set end)

                // *** End programmer edit section *** (ДокСмета.ЦенаЗаЕд Set end)
            }
        }
        
        /// <summary>
        /// Док смета.
        /// </summary>
        // *** Start programmer edit section *** (ДокСмета.ЕдИзмерен CustomAttributes)

        // *** End programmer edit section *** (ДокСмета.ЕдИзмерен CustomAttributes)
        [PropertyStorage(new string[] {
                "ЕдИзмерен"})]
        [NotNull()]
        public virtual IIS.Proekt.ЕдИзмерен ЕдИзмерен
        {
            get
            {
                // *** Start programmer edit section *** (ДокСмета.ЕдИзмерен Get start)

                // *** End programmer edit section *** (ДокСмета.ЕдИзмерен Get start)
                IIS.Proekt.ЕдИзмерен result = this.fЕдИзмерен;
                // *** Start programmer edit section *** (ДокСмета.ЕдИзмерен Get end)

                // *** End programmer edit section *** (ДокСмета.ЕдИзмерен Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокСмета.ЕдИзмерен Set start)

                // *** End programmer edit section *** (ДокСмета.ЕдИзмерен Set start)
                this.fЕдИзмерен = value;
                // *** Start programmer edit section *** (ДокСмета.ЕдИзмерен Set end)

                // *** End programmer edit section *** (ДокСмета.ЕдИзмерен Set end)
            }
        }
        
        /// <summary>
        /// Док смета.
        /// </summary>
        // *** Start programmer edit section *** (ДокСмета.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (ДокСмета.Номенклатура CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенклатура"})]
        [NotNull()]
        public virtual IIS.Proekt.Номенклатура Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (ДокСмета.Номенклатура Get start)

                // *** End programmer edit section *** (ДокСмета.Номенклатура Get start)
                IIS.Proekt.Номенклатура result = this.fНоменклатура;
                // *** Start programmer edit section *** (ДокСмета.Номенклатура Get end)

                // *** End programmer edit section *** (ДокСмета.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокСмета.Номенклатура Set start)

                // *** End programmer edit section *** (ДокСмета.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (ДокСмета.Номенклатура Set end)

                // *** End programmer edit section *** (ДокСмета.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// Док смета.
        /// </summary>
        // *** Start programmer edit section *** (ДокСмета.ОбъектСМР CustomAttributes)

        // *** End programmer edit section *** (ДокСмета.ОбъектСМР CustomAttributes)
        [PropertyStorage(new string[] {
                "ОбъектСМР"})]
        [NotNull()]
        public virtual IIS.Proekt.ОбъектСМР ОбъектСМР
        {
            get
            {
                // *** Start programmer edit section *** (ДокСмета.ОбъектСМР Get start)

                // *** End programmer edit section *** (ДокСмета.ОбъектСМР Get start)
                IIS.Proekt.ОбъектСМР result = this.fОбъектСМР;
                // *** Start programmer edit section *** (ДокСмета.ОбъектСМР Get end)

                // *** End programmer edit section *** (ДокСмета.ОбъектСМР Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокСмета.ОбъектСМР Set start)

                // *** End programmer edit section *** (ДокСмета.ОбъектСМР Set start)
                this.fОбъектСМР = value;
                // *** Start programmer edit section *** (ДокСмета.ОбъектСМР Set end)

                // *** End programmer edit section *** (ДокСмета.ОбъектСМР Set end)
            }
        }
        
        /// <summary>
        /// Док смета.
        /// </summary>
        // *** Start programmer edit section *** (ДокСмета.СпрКонтраг CustomAttributes)

        // *** End programmer edit section *** (ДокСмета.СпрКонтраг CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрКонтраг"})]
        [NotNull()]
        public virtual IIS.Proekt.СпрКонтраг СпрКонтраг
        {
            get
            {
                // *** Start programmer edit section *** (ДокСмета.СпрКонтраг Get start)

                // *** End programmer edit section *** (ДокСмета.СпрКонтраг Get start)
                IIS.Proekt.СпрКонтраг result = this.fСпрКонтраг;
                // *** Start programmer edit section *** (ДокСмета.СпрКонтраг Get end)

                // *** End programmer edit section *** (ДокСмета.СпрКонтраг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокСмета.СпрКонтраг Set start)

                // *** End programmer edit section *** (ДокСмета.СпрКонтраг Set start)
                this.fСпрКонтраг = value;
                // *** Start programmer edit section *** (ДокСмета.СпрКонтраг Set end)

                // *** End programmer edit section *** (ДокСмета.СпрКонтраг Set end)
            }
        }
        
        /// <summary>
        /// Док смета.
        /// </summary>
        // *** Start programmer edit section *** (ДокСмета.ТЧСмета CustomAttributes)

        // *** End programmer edit section *** (ДокСмета.ТЧСмета CustomAttributes)
        public virtual IIS.Proekt.DetailArrayOfТЧСмета ТЧСмета
        {
            get
            {
                // *** Start programmer edit section *** (ДокСмета.ТЧСмета Get start)

                // *** End programmer edit section *** (ДокСмета.ТЧСмета Get start)
                if ((this.fТЧСмета == null))
                {
                    this.fТЧСмета = new IIS.Proekt.DetailArrayOfТЧСмета(this);
                }
                IIS.Proekt.DetailArrayOfТЧСмета result = this.fТЧСмета;
                // *** Start programmer edit section *** (ДокСмета.ТЧСмета Get end)

                // *** End programmer edit section *** (ДокСмета.ТЧСмета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокСмета.ТЧСмета Set start)

                // *** End programmer edit section *** (ДокСмета.ТЧСмета Set start)
                this.fТЧСмета = value;
                // *** Start programmer edit section *** (ДокСмета.ТЧСмета Set end)

                // *** End programmer edit section *** (ДокСмета.ТЧСмета Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокСметаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокСметаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокСметаE", typeof(IIS.Proekt.ДокСмета));
                }
            }
            
            /// <summary>
            /// "ДокСметаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокСметаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокСметаL", typeof(IIS.Proekt.ДокСмета));
                }
            }
        }
    }
}
