//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Док смета.
    /// </summary>
    // *** Start programmer edit section *** (ДокСмета CustomAttributes)

    // *** End programmer edit section *** (ДокСмета CustomAttributes)
    [AutoAltered()]
    [Caption("Документ смета")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокСметаE", new string[] {
            "НомСметРасч as \'Номер сметных расчетов\'",
            "Количество as \'Количество\'",
            "ЦенаЗаЕд as \'Цена за единицу\'",
            "ОбщСметСтои as \'Общая сметная стоимость\'"})]
    [View("ДокСметаL", new string[] {
            "НомСметРасч as \'Номер сметных расчетов\'",
            "Количество as \'Количество\'",
            "ЦенаЗаЕд as \'Цена за единицу\'",
            "ОбщСметСтои as \'Общая сметная стоимость\'"})]
    public class ДокСмета : ICSSoft.STORMNET.DataObject
    {
        
        private float fОбщСметСтои;
        
        private int fКоличество;
        
        private float fЦенаЗаЕд;
        
        private int fНомСметРасч;
        
        // *** Start programmer edit section *** (ДокСмета CustomMembers)

        // *** End programmer edit section *** (ДокСмета CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ДокСмета.Количество CustomAttributes)

        // *** End programmer edit section *** (ДокСмета.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ДокСмета.Количество Get start)

                // *** End programmer edit section *** (ДокСмета.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ДокСмета.Количество Get end)

                // *** End programmer edit section *** (ДокСмета.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокСмета.Количество Set start)

                // *** End programmer edit section *** (ДокСмета.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ДокСмета.Количество Set end)

                // *** End programmer edit section *** (ДокСмета.Количество Set end)
            }
        }
        
        /// <summary>
        /// НомСметРасч.
        /// </summary>
        // *** Start programmer edit section *** (ДокСмета.НомСметРасч CustomAttributes)

        // *** End programmer edit section *** (ДокСмета.НомСметРасч CustomAttributes)
        public virtual int НомСметРасч
        {
            get
            {
                // *** Start programmer edit section *** (ДокСмета.НомСметРасч Get start)

                // *** End programmer edit section *** (ДокСмета.НомСметРасч Get start)
                int result = this.fНомСметРасч;
                // *** Start programmer edit section *** (ДокСмета.НомСметРасч Get end)

                // *** End programmer edit section *** (ДокСмета.НомСметРасч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокСмета.НомСметРасч Set start)

                // *** End programmer edit section *** (ДокСмета.НомСметРасч Set start)
                this.fНомСметРасч = value;
                // *** Start programmer edit section *** (ДокСмета.НомСметРасч Set end)

                // *** End programmer edit section *** (ДокСмета.НомСметРасч Set end)
            }
        }
        
        /// <summary>
        /// ОбщСметСтои.
        /// </summary>
        // *** Start programmer edit section *** (ДокСмета.ОбщСметСтои CustomAttributes)

        // *** End programmer edit section *** (ДокСмета.ОбщСметСтои CustomAttributes)
        public virtual float ОбщСметСтои
        {
            get
            {
                // *** Start programmer edit section *** (ДокСмета.ОбщСметСтои Get start)

                // *** End programmer edit section *** (ДокСмета.ОбщСметСтои Get start)
                float result = this.fОбщСметСтои;
                // *** Start programmer edit section *** (ДокСмета.ОбщСметСтои Get end)

                // *** End programmer edit section *** (ДокСмета.ОбщСметСтои Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокСмета.ОбщСметСтои Set start)

                // *** End programmer edit section *** (ДокСмета.ОбщСметСтои Set start)
                this.fОбщСметСтои = value;
                // *** Start programmer edit section *** (ДокСмета.ОбщСметСтои Set end)

                // *** End programmer edit section *** (ДокСмета.ОбщСметСтои Set end)
            }
        }
        
        /// <summary>
        /// ЦенаЗаЕд.
        /// </summary>
        // *** Start programmer edit section *** (ДокСмета.ЦенаЗаЕд CustomAttributes)

        // *** End programmer edit section *** (ДокСмета.ЦенаЗаЕд CustomAttributes)
        public virtual float ЦенаЗаЕд
        {
            get
            {
                // *** Start programmer edit section *** (ДокСмета.ЦенаЗаЕд Get start)

                // *** End programmer edit section *** (ДокСмета.ЦенаЗаЕд Get start)
                float result = this.fЦенаЗаЕд;
                // *** Start programmer edit section *** (ДокСмета.ЦенаЗаЕд Get end)

                // *** End programmer edit section *** (ДокСмета.ЦенаЗаЕд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокСмета.ЦенаЗаЕд Set start)

                // *** End programmer edit section *** (ДокСмета.ЦенаЗаЕд Set start)
                this.fЦенаЗаЕд = value;
                // *** Start programmer edit section *** (ДокСмета.ЦенаЗаЕд Set end)

                // *** End programmer edit section *** (ДокСмета.ЦенаЗаЕд Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокСметаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокСметаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокСметаE", typeof(IIS.Proekt.ДокСмета));
                }
            }
            
            /// <summary>
            /// "ДокСметаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокСметаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокСметаL", typeof(IIS.Proekt.ДокСмета));
                }
            }
        }
    }
}
