//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Док услов дог.
    /// </summary>
    // *** Start programmer edit section *** (ДокУсловДог CustomAttributes)

    // *** End programmer edit section *** (ДокУсловДог CustomAttributes)
    [AutoAltered()]
    [Caption("Документ условия договора")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокУсловДогE", new string[] {
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончан as \'Дата окончания\'",
            "Длительность as \'Длительность\'",
            "СумПоДогов as \'Сумма по договору\'"})]
    [View("ДокУсловДогL", new string[] {
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончан as \'Дата окончания\'",
            "Длительность as \'Длительность\'",
            "СумПоДогов as \'Сумма по договору\'"})]
    public class ДокУсловДог : ICSSoft.STORMNET.DataObject
    {
        
        private int fДлительность;
        
        private float fСумПоДогов;
        
        private System.DateTime fДатаНачала;
        
        private System.DateTime fДатаОкончан;
        
        // *** Start programmer edit section *** (ДокУсловДог CustomMembers)

        // *** End programmer edit section *** (ДокУсловДог CustomMembers)

        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (ДокУсловДог.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (ДокУсловДог.ДатаНачала CustomAttributes)
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (ДокУсловДог.ДатаНачала Get start)

                // *** End programmer edit section *** (ДокУсловДог.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (ДокУсловДог.ДатаНачала Get end)

                // *** End programmer edit section *** (ДокУсловДог.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокУсловДог.ДатаНачала Set start)

                // *** End programmer edit section *** (ДокУсловДог.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (ДокУсловДог.ДатаНачала Set end)

                // *** End programmer edit section *** (ДокУсловДог.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончан.
        /// </summary>
        // *** Start programmer edit section *** (ДокУсловДог.ДатаОкончан CustomAttributes)

        // *** End programmer edit section *** (ДокУсловДог.ДатаОкончан CustomAttributes)
        public virtual System.DateTime ДатаОкончан
        {
            get
            {
                // *** Start programmer edit section *** (ДокУсловДог.ДатаОкончан Get start)

                // *** End programmer edit section *** (ДокУсловДог.ДатаОкончан Get start)
                System.DateTime result = this.fДатаОкончан;
                // *** Start programmer edit section *** (ДокУсловДог.ДатаОкончан Get end)

                // *** End programmer edit section *** (ДокУсловДог.ДатаОкончан Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокУсловДог.ДатаОкончан Set start)

                // *** End programmer edit section *** (ДокУсловДог.ДатаОкончан Set start)
                this.fДатаОкончан = value;
                // *** Start programmer edit section *** (ДокУсловДог.ДатаОкончан Set end)

                // *** End programmer edit section *** (ДокУсловДог.ДатаОкончан Set end)
            }
        }
        
        /// <summary>
        /// Длительность.
        /// </summary>
        // *** Start programmer edit section *** (ДокУсловДог.Длительность CustomAttributes)

        // *** End programmer edit section *** (ДокУсловДог.Длительность CustomAttributes)
        public virtual int Длительность
        {
            get
            {
                // *** Start programmer edit section *** (ДокУсловДог.Длительность Get start)

                // *** End programmer edit section *** (ДокУсловДог.Длительность Get start)
                int result = this.fДлительность;
                // *** Start programmer edit section *** (ДокУсловДог.Длительность Get end)

                // *** End programmer edit section *** (ДокУсловДог.Длительность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокУсловДог.Длительность Set start)

                // *** End programmer edit section *** (ДокУсловДог.Длительность Set start)
                this.fДлительность = value;
                // *** Start programmer edit section *** (ДокУсловДог.Длительность Set end)

                // *** End programmer edit section *** (ДокУсловДог.Длительность Set end)
            }
        }
        
        /// <summary>
        /// СумПоДогов.
        /// </summary>
        // *** Start programmer edit section *** (ДокУсловДог.СумПоДогов CustomAttributes)

        // *** End programmer edit section *** (ДокУсловДог.СумПоДогов CustomAttributes)
        public virtual float СумПоДогов
        {
            get
            {
                // *** Start programmer edit section *** (ДокУсловДог.СумПоДогов Get start)

                // *** End programmer edit section *** (ДокУсловДог.СумПоДогов Get start)
                float result = this.fСумПоДогов;
                // *** Start programmer edit section *** (ДокУсловДог.СумПоДогов Get end)

                // *** End programmer edit section *** (ДокУсловДог.СумПоДогов Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокУсловДог.СумПоДогов Set start)

                // *** End programmer edit section *** (ДокУсловДог.СумПоДогов Set start)
                this.fСумПоДогов = value;
                // *** Start programmer edit section *** (ДокУсловДог.СумПоДогов Set end)

                // *** End programmer edit section *** (ДокУсловДог.СумПоДогов Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокУсловДогE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокУсловДогE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокУсловДогE", typeof(IIS.Proekt.ДокУсловДог));
                }
            }
            
            /// <summary>
            /// "ДокУсловДогL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокУсловДогL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокУсловДогL", typeof(IIS.Proekt.ДокУсловДог));
                }
            }
        }
    }
}
