//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Номенклатура.
    /// </summary>
    // *** Start programmer edit section *** (Номенклатура CustomAttributes)

    // *** End programmer edit section *** (Номенклатура CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НоменклатураE", new string[] {
            "Код as \'Код\'",
            "Наименов as \'Наименование\'",
            "Описание as \'Описание\'"})]
    [View("НоменклатураL", new string[] {
            "Код as \'Код\'",
            "Наименов as \'Наименование\'",
            "Описание as \'Описание\'"})]
    public class Номенклатура : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fНаименов;
        
        private string fОписание;
        
        // *** Start programmer edit section *** (Номенклатура CustomMembers)

        // *** End programmer edit section *** (Номенклатура CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.Код CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.Код Get start)

                // *** End programmer edit section *** (Номенклатура.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Номенклатура.Код Get end)

                // *** End programmer edit section *** (Номенклатура.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.Код Set start)

                // *** End programmer edit section *** (Номенклатура.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Номенклатура.Код Set end)

                // *** End programmer edit section *** (Номенклатура.Код Set end)
            }
        }
        
        /// <summary>
        /// Наименов.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.Наименов CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.Наименов CustomAttributes)
        [StrLen(255)]
        public virtual string Наименов
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.Наименов Get start)

                // *** End programmer edit section *** (Номенклатура.Наименов Get start)
                string result = this.fНаименов;
                // *** Start programmer edit section *** (Номенклатура.Наименов Get end)

                // *** End programmer edit section *** (Номенклатура.Наименов Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.Наименов Set start)

                // *** End programmer edit section *** (Номенклатура.Наименов Set start)
                this.fНаименов = value;
                // *** Start programmer edit section *** (Номенклатура.Наименов Set end)

                // *** End programmer edit section *** (Номенклатура.Наименов Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.Описание CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.Описание Get start)

                // *** End programmer edit section *** (Номенклатура.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (Номенклатура.Описание Get end)

                // *** End programmer edit section *** (Номенклатура.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.Описание Set start)

                // *** End programmer edit section *** (Номенклатура.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (Номенклатура.Описание Set end)

                // *** End programmer edit section *** (Номенклатура.Описание Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НоменклатураE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатураE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатураE", typeof(IIS.Proekt.Номенклатура));
                }
            }
            
            /// <summary>
            /// "НоменклатураL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатураL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатураL", typeof(IIS.Proekt.Номенклатура));
                }
            }
        }
    }
}
