//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Объект СМР.
    /// </summary>
    // *** Start programmer edit section *** (ОбъектСМР CustomAttributes)

    // *** End programmer edit section *** (ОбъектСМР CustomAttributes)
    [AutoAltered()]
    [Caption("Объекты СМР")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОбъектСМРE", new string[] {
            "Код as \'Код\'",
            "ОбъектСтроит as \'Объект строительства\'"})]
    [View("ОбъектСМРL", new string[] {
            "Код as \'Код\'",
            "ОбъектСтроит as \'Объект строительства\'"})]
    public class ОбъектСМР : ICSSoft.STORMNET.DataObject
    {
        
        private string fОбъектСтроит;
        
        private int fКод;
        
        // *** Start programmer edit section *** (ОбъектСМР CustomMembers)

        // *** End programmer edit section *** (ОбъектСМР CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектСМР.Код CustomAttributes)

        // *** End programmer edit section *** (ОбъектСМР.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектСМР.Код Get start)

                // *** End programmer edit section *** (ОбъектСМР.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (ОбъектСМР.Код Get end)

                // *** End programmer edit section *** (ОбъектСМР.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектСМР.Код Set start)

                // *** End programmer edit section *** (ОбъектСМР.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (ОбъектСМР.Код Set end)

                // *** End programmer edit section *** (ОбъектСМР.Код Set end)
            }
        }
        
        /// <summary>
        /// ОбъектСтроит.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектСМР.ОбъектСтроит CustomAttributes)

        // *** End programmer edit section *** (ОбъектСМР.ОбъектСтроит CustomAttributes)
        [StrLen(255)]
        public virtual string ОбъектСтроит
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектСМР.ОбъектСтроит Get start)

                // *** End programmer edit section *** (ОбъектСМР.ОбъектСтроит Get start)
                string result = this.fОбъектСтроит;
                // *** Start programmer edit section *** (ОбъектСМР.ОбъектСтроит Get end)

                // *** End programmer edit section *** (ОбъектСМР.ОбъектСтроит Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектСМР.ОбъектСтроит Set start)

                // *** End programmer edit section *** (ОбъектСМР.ОбъектСтроит Set start)
                this.fОбъектСтроит = value;
                // *** Start programmer edit section *** (ОбъектСМР.ОбъектСтроит Set end)

                // *** End programmer edit section *** (ОбъектСМР.ОбъектСтроит Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОбъектСМРE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбъектСМРE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбъектСМРE", typeof(IIS.Proekt.ОбъектСМР));
                }
            }
            
            /// <summary>
            /// "ОбъектСМРL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбъектСМРL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбъектСМРL", typeof(IIS.Proekt.ОбъектСМР));
                }
            }
        }
    }
}
