//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// От по вып догов.
    /// </summary>
    // *** Start programmer edit section *** (ОтПоВыпДогов CustomAttributes)

    // *** End programmer edit section *** (ОтПоВыпДогов CustomAttributes)
    [AutoAltered()]
    [Caption("Отчет по выполнению договоров")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтПоВыпДоговE", new string[] {
            "Выполнение as \'Выполнение\'",
            "СумКонечОстат as \'Сумма конечный остаток\'",
            "Сотрудники as \'Сотрудник\'",
            "Сотрудники.ФИО as \'Сотрудник\'"})]
    [View("ОтПоВыпДоговL", new string[] {
            "Выполнение as \'Выполнение\'",
            "СумКонечОстат as \'Сумма конечный остаток\'",
            "Сотрудники.ФИО as \'Сотрудник\'"})]
    public class ОтПоВыпДогов : ICSSoft.STORMNET.DataObject
    {
        
        private float fСумКонечОстат;
        
        private float fВыполнение;
        
        private IIS.Proekt.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ОтПоВыпДогов CustomMembers)

        // *** End programmer edit section *** (ОтПоВыпДогов CustomMembers)

        
        /// <summary>
        /// Выполнение.
        /// </summary>
        // *** Start programmer edit section *** (ОтПоВыпДогов.Выполнение CustomAttributes)

        // *** End programmer edit section *** (ОтПоВыпДогов.Выполнение CustomAttributes)
        public virtual float Выполнение
        {
            get
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.Выполнение Get start)

                // *** End programmer edit section *** (ОтПоВыпДогов.Выполнение Get start)
                float result = this.fВыполнение;
                // *** Start programmer edit section *** (ОтПоВыпДогов.Выполнение Get end)

                // *** End programmer edit section *** (ОтПоВыпДогов.Выполнение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.Выполнение Set start)

                // *** End programmer edit section *** (ОтПоВыпДогов.Выполнение Set start)
                this.fВыполнение = value;
                // *** Start programmer edit section *** (ОтПоВыпДогов.Выполнение Set end)

                // *** End programmer edit section *** (ОтПоВыпДогов.Выполнение Set end)
            }
        }
        
        /// <summary>
        /// СумКонечОстат.
        /// </summary>
        // *** Start programmer edit section *** (ОтПоВыпДогов.СумКонечОстат CustomAttributes)

        // *** End programmer edit section *** (ОтПоВыпДогов.СумКонечОстат CustomAttributes)
        public virtual float СумКонечОстат
        {
            get
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.СумКонечОстат Get start)

                // *** End programmer edit section *** (ОтПоВыпДогов.СумКонечОстат Get start)
                float result = this.fСумКонечОстат;
                // *** Start programmer edit section *** (ОтПоВыпДогов.СумКонечОстат Get end)

                // *** End programmer edit section *** (ОтПоВыпДогов.СумКонечОстат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.СумКонечОстат Set start)

                // *** End programmer edit section *** (ОтПоВыпДогов.СумКонечОстат Set start)
                this.fСумКонечОстат = value;
                // *** Start programmer edit section *** (ОтПоВыпДогов.СумКонечОстат Set end)

                // *** End programmer edit section *** (ОтПоВыпДогов.СумКонечОстат Set end)
            }
        }
        
        /// <summary>
        /// От по вып догов.
        /// </summary>
        // *** Start programmer edit section *** (ОтПоВыпДогов.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ОтПоВыпДогов.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Proekt.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.Сотрудники Get start)

                // *** End programmer edit section *** (ОтПоВыпДогов.Сотрудники Get start)
                IIS.Proekt.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ОтПоВыпДогов.Сотрудники Get end)

                // *** End programmer edit section *** (ОтПоВыпДогов.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.Сотрудники Set start)

                // *** End programmer edit section *** (ОтПоВыпДогов.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ОтПоВыпДогов.Сотрудники Set end)

                // *** End programmer edit section *** (ОтПоВыпДогов.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтПоВыпДоговE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтПоВыпДоговE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтПоВыпДоговE", typeof(IIS.Proekt.ОтПоВыпДогов));
                }
            }
            
            /// <summary>
            /// "ОтПоВыпДоговL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтПоВыпДоговL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтПоВыпДоговL", typeof(IIS.Proekt.ОтПоВыпДогов));
                }
            }
        }
    }
}
