//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отч о рас ос мат.
    /// </summary>
    // *** Start programmer edit section *** (ОтчОРасОсМат CustomAttributes)

    // *** End programmer edit section *** (ОтчОРасОсМат CustomAttributes)
    [AutoAltered()]
    [Caption("Отчет о расходах основных материалов")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчОРасОсМатE", new string[] {
            "НормаРасхода as \'Норма расхода\'",
            "КолПоАктТек as \'Количество по актам текущий\'",
            "СуммаИтого as \'Сумма итого\'",
            "Сотрудники as \'Сотрудник\'",
            "Сотрудники.ФИО as \'Сотрудник\'"})]
    [View("ОтчОРасОсМатL", new string[] {
            "НормаРасхода as \'Норма расхода\'",
            "КолПоАктТек as \'Количество по актам текущий\'",
            "СуммаИтого as \'Сумма итого\'",
            "Сотрудники.ФИО as \'Сотрудники\'"})]
    public class ОтчОРасОсМат : ICSSoft.STORMNET.DataObject
    {
        
        private int fКолПоАктТек;
        
        private int fНормаРасхода;
        
        private float fСуммаИтого;
        
        private IIS.Proekt.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ОтчОРасОсМат CustomMembers)

        // *** End programmer edit section *** (ОтчОРасОсМат CustomMembers)

        
        /// <summary>
        /// КолПоАктТек.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОРасОсМат.КолПоАктТек CustomAttributes)

        // *** End programmer edit section *** (ОтчОРасОсМат.КолПоАктТек CustomAttributes)
        public virtual int КолПоАктТек
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.КолПоАктТек Get start)

                // *** End programmer edit section *** (ОтчОРасОсМат.КолПоАктТек Get start)
                int result = this.fКолПоАктТек;
                // *** Start programmer edit section *** (ОтчОРасОсМат.КолПоАктТек Get end)

                // *** End programmer edit section *** (ОтчОРасОсМат.КолПоАктТек Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.КолПоАктТек Set start)

                // *** End programmer edit section *** (ОтчОРасОсМат.КолПоАктТек Set start)
                this.fКолПоАктТек = value;
                // *** Start programmer edit section *** (ОтчОРасОсМат.КолПоАктТек Set end)

                // *** End programmer edit section *** (ОтчОРасОсМат.КолПоАктТек Set end)
            }
        }
        
        /// <summary>
        /// НормаРасхода.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОРасОсМат.НормаРасхода CustomAttributes)

        // *** End programmer edit section *** (ОтчОРасОсМат.НормаРасхода CustomAttributes)
        public virtual int НормаРасхода
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.НормаРасхода Get start)

                // *** End programmer edit section *** (ОтчОРасОсМат.НормаРасхода Get start)
                int result = this.fНормаРасхода;
                // *** Start programmer edit section *** (ОтчОРасОсМат.НормаРасхода Get end)

                // *** End programmer edit section *** (ОтчОРасОсМат.НормаРасхода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.НормаРасхода Set start)

                // *** End programmer edit section *** (ОтчОРасОсМат.НормаРасхода Set start)
                this.fНормаРасхода = value;
                // *** Start programmer edit section *** (ОтчОРасОсМат.НормаРасхода Set end)

                // *** End programmer edit section *** (ОтчОРасОсМат.НормаРасхода Set end)
            }
        }
        
        /// <summary>
        /// СуммаИтого.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОРасОсМат.СуммаИтого CustomAttributes)

        // *** End programmer edit section *** (ОтчОРасОсМат.СуммаИтого CustomAttributes)
        public virtual float СуммаИтого
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.СуммаИтого Get start)

                // *** End programmer edit section *** (ОтчОРасОсМат.СуммаИтого Get start)
                float result = this.fСуммаИтого;
                // *** Start programmer edit section *** (ОтчОРасОсМат.СуммаИтого Get end)

                // *** End programmer edit section *** (ОтчОРасОсМат.СуммаИтого Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.СуммаИтого Set start)

                // *** End programmer edit section *** (ОтчОРасОсМат.СуммаИтого Set start)
                this.fСуммаИтого = value;
                // *** Start programmer edit section *** (ОтчОРасОсМат.СуммаИтого Set end)

                // *** End programmer edit section *** (ОтчОРасОсМат.СуммаИтого Set end)
            }
        }
        
        /// <summary>
        /// Отч о рас ос мат.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОРасОсМат.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ОтчОРасОсМат.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Proekt.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.Сотрудники Get start)

                // *** End programmer edit section *** (ОтчОРасОсМат.Сотрудники Get start)
                IIS.Proekt.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ОтчОРасОсМат.Сотрудники Get end)

                // *** End programmer edit section *** (ОтчОРасОсМат.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.Сотрудники Set start)

                // *** End programmer edit section *** (ОтчОРасОсМат.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ОтчОРасОсМат.Сотрудники Set end)

                // *** End programmer edit section *** (ОтчОРасОсМат.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчОРасОсМатE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчОРасОсМатE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчОРасОсМатE", typeof(IIS.Proekt.ОтчОРасОсМат));
                }
            }
            
            /// <summary>
            /// "ОтчОРасОсМатL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчОРасОсМатL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчОРасОсМатL", typeof(IIS.Proekt.ОтчОРасОсМат));
                }
            }
        }
    }
}
