//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// От по вып догов.
    /// </summary>
    // *** Start programmer edit section *** (ОтПоВыпДогов CustomAttributes)

    // *** End programmer edit section *** (ОтПоВыпДогов CustomAttributes)
    [AutoAltered()]
    [Caption("Отчет по выполнению договоров")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтПоВыпДоговE", new string[] {
            "НомерДогово as \'Номер договора\'",
            "ОбъектСМР as \'Объект строительства\'",
            "ОбъектСМР.ОбъектСтроит as \'Объект строительства\'",
            "Сотрудники as \'Сотрудник\'",
            "Сотрудники.ФИО as \'Сотрудник\'",
            "СпрКонтраг as \'Контрагент\'",
            "СпрКонтраг.Наименование as \'Контрагент\'",
            "ДокСмета as \'Объем работ по смете\'",
            "ДокСмета.ОбРабПоСмет as \'Объем работ по смете\'",
            "ДокУсловДог as \'Сумма по договору\'",
            "ДокУсловДог.СумПоДогов as \'Сумма по договору\'",
            "Выполнение as \'Выполнение\'",
            "СумКонечОстат as \'Сумма конечный остаток\'"})]
    [View("ОтПоВыпДоговL", new string[] {
            "Сотрудники.ФИО as \'Сотрудник\'",
            "НомерДогово as \'Номер договора\'",
            "ОбъектСМР.ОбъектСтроит as \'Объект строительства\'",
            "СпрКонтраг.Наименование as \'Котрагент\'",
            "ДокСмета.ОбРабПоСмет as \'Объем работ по смете\'",
            "ДокУсловДог.СумПоДогов as \'Сумма по договору\'",
            "Выполнение as \'Выполнение\'",
            "СумКонечОстат as \'Сумма конечный остаток\'"})]
    public class ОтПоВыпДогов : ICSSoft.STORMNET.DataObject
    {
        
        private float fСумКонечОстат;
        
        private float fВыполнение;
        
        private int fНомерДогово;
        
        private IIS.Proekt.ДокУсловДог fДокУсловДог;
        
        private IIS.Proekt.СпрКонтраг fСпрКонтраг;
        
        private IIS.Proekt.Сотрудники fСотрудники;
        
        private IIS.Proekt.ДокСмета fДокСмета;
        
        private IIS.Proekt.ОбъектСМР fОбъектСМР;
        
        // *** Start programmer edit section *** (ОтПоВыпДогов CustomMembers)

        // *** End programmer edit section *** (ОтПоВыпДогов CustomMembers)

        
        /// <summary>
        /// Выполнение.
        /// </summary>
        // *** Start programmer edit section *** (ОтПоВыпДогов.Выполнение CustomAttributes)

        // *** End programmer edit section *** (ОтПоВыпДогов.Выполнение CustomAttributes)
        public virtual float Выполнение
        {
            get
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.Выполнение Get start)

                // *** End programmer edit section *** (ОтПоВыпДогов.Выполнение Get start)
                float result = this.fВыполнение;
                // *** Start programmer edit section *** (ОтПоВыпДогов.Выполнение Get end)

                // *** End programmer edit section *** (ОтПоВыпДогов.Выполнение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.Выполнение Set start)

                // *** End programmer edit section *** (ОтПоВыпДогов.Выполнение Set start)
                this.fВыполнение = value;
                // *** Start programmer edit section *** (ОтПоВыпДогов.Выполнение Set end)

                // *** End programmer edit section *** (ОтПоВыпДогов.Выполнение Set end)
            }
        }
        
        /// <summary>
        /// НомерДогово.
        /// </summary>
        // *** Start programmer edit section *** (ОтПоВыпДогов.НомерДогово CustomAttributes)

        // *** End programmer edit section *** (ОтПоВыпДогов.НомерДогово CustomAttributes)
        public virtual int НомерДогово
        {
            get
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.НомерДогово Get start)

                // *** End programmer edit section *** (ОтПоВыпДогов.НомерДогово Get start)
                int result = this.fНомерДогово;
                // *** Start programmer edit section *** (ОтПоВыпДогов.НомерДогово Get end)

                // *** End programmer edit section *** (ОтПоВыпДогов.НомерДогово Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.НомерДогово Set start)

                // *** End programmer edit section *** (ОтПоВыпДогов.НомерДогово Set start)
                this.fНомерДогово = value;
                // *** Start programmer edit section *** (ОтПоВыпДогов.НомерДогово Set end)

                // *** End programmer edit section *** (ОтПоВыпДогов.НомерДогово Set end)
            }
        }
        
        /// <summary>
        /// СумКонечОстат.
        /// </summary>
        // *** Start programmer edit section *** (ОтПоВыпДогов.СумКонечОстат CustomAttributes)

        // *** End programmer edit section *** (ОтПоВыпДогов.СумКонечОстат CustomAttributes)
        public virtual float СумКонечОстат
        {
            get
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.СумКонечОстат Get start)

                // *** End programmer edit section *** (ОтПоВыпДогов.СумКонечОстат Get start)
                float result = this.fСумКонечОстат;
                // *** Start programmer edit section *** (ОтПоВыпДогов.СумКонечОстат Get end)

                // *** End programmer edit section *** (ОтПоВыпДогов.СумКонечОстат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.СумКонечОстат Set start)

                // *** End programmer edit section *** (ОтПоВыпДогов.СумКонечОстат Set start)
                this.fСумКонечОстат = value;
                // *** Start programmer edit section *** (ОтПоВыпДогов.СумКонечОстат Set end)

                // *** End programmer edit section *** (ОтПоВыпДогов.СумКонечОстат Set end)
            }
        }
        
        /// <summary>
        /// От по вып догов.
        /// </summary>
        // *** Start programmer edit section *** (ОтПоВыпДогов.ДокСмета CustomAttributes)

        // *** End programmer edit section *** (ОтПоВыпДогов.ДокСмета CustomAttributes)
        [PropertyStorage(new string[] {
                "ДокСмета"})]
        [NotNull()]
        public virtual IIS.Proekt.ДокСмета ДокСмета
        {
            get
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.ДокСмета Get start)

                // *** End programmer edit section *** (ОтПоВыпДогов.ДокСмета Get start)
                IIS.Proekt.ДокСмета result = this.fДокСмета;
                // *** Start programmer edit section *** (ОтПоВыпДогов.ДокСмета Get end)

                // *** End programmer edit section *** (ОтПоВыпДогов.ДокСмета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.ДокСмета Set start)

                // *** End programmer edit section *** (ОтПоВыпДогов.ДокСмета Set start)
                this.fДокСмета = value;
                // *** Start programmer edit section *** (ОтПоВыпДогов.ДокСмета Set end)

                // *** End programmer edit section *** (ОтПоВыпДогов.ДокСмета Set end)
            }
        }
        
        /// <summary>
        /// От по вып догов.
        /// </summary>
        // *** Start programmer edit section *** (ОтПоВыпДогов.ДокУсловДог CustomAttributes)

        // *** End programmer edit section *** (ОтПоВыпДогов.ДокУсловДог CustomAttributes)
        [PropertyStorage(new string[] {
                "ДокУсловДог"})]
        [NotNull()]
        public virtual IIS.Proekt.ДокУсловДог ДокУсловДог
        {
            get
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.ДокУсловДог Get start)

                // *** End programmer edit section *** (ОтПоВыпДогов.ДокУсловДог Get start)
                IIS.Proekt.ДокУсловДог result = this.fДокУсловДог;
                // *** Start programmer edit section *** (ОтПоВыпДогов.ДокУсловДог Get end)

                // *** End programmer edit section *** (ОтПоВыпДогов.ДокУсловДог Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.ДокУсловДог Set start)

                // *** End programmer edit section *** (ОтПоВыпДогов.ДокУсловДог Set start)
                this.fДокУсловДог = value;
                // *** Start programmer edit section *** (ОтПоВыпДогов.ДокУсловДог Set end)

                // *** End programmer edit section *** (ОтПоВыпДогов.ДокУсловДог Set end)
            }
        }
        
        /// <summary>
        /// От по вып догов.
        /// </summary>
        // *** Start programmer edit section *** (ОтПоВыпДогов.ОбъектСМР CustomAttributes)

        // *** End programmer edit section *** (ОтПоВыпДогов.ОбъектСМР CustomAttributes)
        [PropertyStorage(new string[] {
                "ОбъектСМР"})]
        [NotNull()]
        public virtual IIS.Proekt.ОбъектСМР ОбъектСМР
        {
            get
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.ОбъектСМР Get start)

                // *** End programmer edit section *** (ОтПоВыпДогов.ОбъектСМР Get start)
                IIS.Proekt.ОбъектСМР result = this.fОбъектСМР;
                // *** Start programmer edit section *** (ОтПоВыпДогов.ОбъектСМР Get end)

                // *** End programmer edit section *** (ОтПоВыпДогов.ОбъектСМР Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.ОбъектСМР Set start)

                // *** End programmer edit section *** (ОтПоВыпДогов.ОбъектСМР Set start)
                this.fОбъектСМР = value;
                // *** Start programmer edit section *** (ОтПоВыпДогов.ОбъектСМР Set end)

                // *** End programmer edit section *** (ОтПоВыпДогов.ОбъектСМР Set end)
            }
        }
        
        /// <summary>
        /// От по вып догов.
        /// </summary>
        // *** Start programmer edit section *** (ОтПоВыпДогов.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ОтПоВыпДогов.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Proekt.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.Сотрудники Get start)

                // *** End programmer edit section *** (ОтПоВыпДогов.Сотрудники Get start)
                IIS.Proekt.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ОтПоВыпДогов.Сотрудники Get end)

                // *** End programmer edit section *** (ОтПоВыпДогов.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.Сотрудники Set start)

                // *** End programmer edit section *** (ОтПоВыпДогов.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ОтПоВыпДогов.Сотрудники Set end)

                // *** End programmer edit section *** (ОтПоВыпДогов.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// От по вып догов.
        /// </summary>
        // *** Start programmer edit section *** (ОтПоВыпДогов.СпрКонтраг CustomAttributes)

        // *** End programmer edit section *** (ОтПоВыпДогов.СпрКонтраг CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрКонтраг"})]
        [NotNull()]
        public virtual IIS.Proekt.СпрКонтраг СпрКонтраг
        {
            get
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.СпрКонтраг Get start)

                // *** End programmer edit section *** (ОтПоВыпДогов.СпрКонтраг Get start)
                IIS.Proekt.СпрКонтраг result = this.fСпрКонтраг;
                // *** Start programmer edit section *** (ОтПоВыпДогов.СпрКонтраг Get end)

                // *** End programmer edit section *** (ОтПоВыпДогов.СпрКонтраг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтПоВыпДогов.СпрКонтраг Set start)

                // *** End programmer edit section *** (ОтПоВыпДогов.СпрКонтраг Set start)
                this.fСпрКонтраг = value;
                // *** Start programmer edit section *** (ОтПоВыпДогов.СпрКонтраг Set end)

                // *** End programmer edit section *** (ОтПоВыпДогов.СпрКонтраг Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтПоВыпДоговE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтПоВыпДоговE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтПоВыпДоговE", typeof(IIS.Proekt.ОтПоВыпДогов));
                }
            }
            
            /// <summary>
            /// "ОтПоВыпДоговL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтПоВыпДоговL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтПоВыпДоговL", typeof(IIS.Proekt.ОтПоВыпДогов));
                }
            }
        }
    }
}
