//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отч о рас ос мат.
    /// </summary>
    // *** Start programmer edit section *** (ОтчОРасОсМат CustomAttributes)

    // *** End programmer edit section *** (ОтчОРасОсМат CustomAttributes)
    [AutoAltered()]
    [Caption("Отчет о расходах основных материалов")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчОРасОсМатE", new string[] {
            "НормаРасхода as \'Норма расхода\'",
            "КолПоАктТек as \'Количество по актам текущий\'",
            "СуммаИтого as \'Сумма итого\'",
            "Сотрудники as \'Сотрудник\'",
            "Сотрудники.ФИО as \'Сотрудник\'",
            "Номенклатура as \'Номенклатура\'",
            "Номенклатура.Наименов as \'Номенклатура\'",
            "РасхМатВСтро as \'Количество по актам всего\'",
            "РасхМатВСтро.Количество as \'Количество по актам всего\'",
            "ДокСмета as \'Количество по смете\'",
            "ДокСмета.Количество as \'Количество по смете\'"})]
    [View("ОтчОРасОсМатL", new string[] {
            "НормаРасхода as \'Норма расхода\'",
            "КолПоАктТек as \'Количество по актам текущий\'",
            "СуммаИтого as \'Сумма итого\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'Сотрудники\'",
            "Номенклатура.Наименов as \'Номенклатура\'",
            "РасхМатВСтро.Количество as \'Количество по актам всего\'",
            "ДокСмета.Количество as \'Количество по смете\'"})]
    public class ОтчОРасОсМат : ICSSoft.STORMNET.DataObject
    {
        
        private int fКолПоАктТек;
        
        private int fНормаРасхода;
        
        private float fСуммаИтого;
        
        private IIS.Proekt.ДокСмета fДокСмета;
        
        private IIS.Proekt.Номенклатура fНоменклатура;
        
        private IIS.Proekt.РасхМатВСтро fРасхМатВСтро;
        
        private IIS.Proekt.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ОтчОРасОсМат CustomMembers)

        // *** End programmer edit section *** (ОтчОРасОсМат CustomMembers)

        
        /// <summary>
        /// КолПоАктТек.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОРасОсМат.КолПоАктТек CustomAttributes)

        // *** End programmer edit section *** (ОтчОРасОсМат.КолПоАктТек CustomAttributes)
        public virtual int КолПоАктТек
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.КолПоАктТек Get start)

                // *** End programmer edit section *** (ОтчОРасОсМат.КолПоАктТек Get start)
                int result = this.fКолПоАктТек;
                // *** Start programmer edit section *** (ОтчОРасОсМат.КолПоАктТек Get end)

                // *** End programmer edit section *** (ОтчОРасОсМат.КолПоАктТек Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.КолПоАктТек Set start)

                // *** End programmer edit section *** (ОтчОРасОсМат.КолПоАктТек Set start)
                this.fКолПоАктТек = value;
                // *** Start programmer edit section *** (ОтчОРасОсМат.КолПоАктТек Set end)

                // *** End programmer edit section *** (ОтчОРасОсМат.КолПоАктТек Set end)
            }
        }
        
        /// <summary>
        /// НормаРасхода.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОРасОсМат.НормаРасхода CustomAttributes)

        // *** End programmer edit section *** (ОтчОРасОсМат.НормаРасхода CustomAttributes)
        public virtual int НормаРасхода
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.НормаРасхода Get start)

                // *** End programmer edit section *** (ОтчОРасОсМат.НормаРасхода Get start)
                int result = this.fНормаРасхода;
                // *** Start programmer edit section *** (ОтчОРасОсМат.НормаРасхода Get end)

                // *** End programmer edit section *** (ОтчОРасОсМат.НормаРасхода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.НормаРасхода Set start)

                // *** End programmer edit section *** (ОтчОРасОсМат.НормаРасхода Set start)
                this.fНормаРасхода = value;
                // *** Start programmer edit section *** (ОтчОРасОсМат.НормаРасхода Set end)

                // *** End programmer edit section *** (ОтчОРасОсМат.НормаРасхода Set end)
            }
        }
        
        /// <summary>
        /// СуммаИтого.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОРасОсМат.СуммаИтого CustomAttributes)

        // *** End programmer edit section *** (ОтчОРасОсМат.СуммаИтого CustomAttributes)
        public virtual float СуммаИтого
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.СуммаИтого Get start)

                // *** End programmer edit section *** (ОтчОРасОсМат.СуммаИтого Get start)
                float result = this.fСуммаИтого;
                // *** Start programmer edit section *** (ОтчОРасОсМат.СуммаИтого Get end)

                // *** End programmer edit section *** (ОтчОРасОсМат.СуммаИтого Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.СуммаИтого Set start)

                // *** End programmer edit section *** (ОтчОРасОсМат.СуммаИтого Set start)
                this.fСуммаИтого = value;
                // *** Start programmer edit section *** (ОтчОРасОсМат.СуммаИтого Set end)

                // *** End programmer edit section *** (ОтчОРасОсМат.СуммаИтого Set end)
            }
        }
        
        /// <summary>
        /// Отч о рас ос мат.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОРасОсМат.ДокСмета CustomAttributes)

        // *** End programmer edit section *** (ОтчОРасОсМат.ДокСмета CustomAttributes)
        [PropertyStorage(new string[] {
                "ДокСмета"})]
        [NotNull()]
        public virtual IIS.Proekt.ДокСмета ДокСмета
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.ДокСмета Get start)

                // *** End programmer edit section *** (ОтчОРасОсМат.ДокСмета Get start)
                IIS.Proekt.ДокСмета result = this.fДокСмета;
                // *** Start programmer edit section *** (ОтчОРасОсМат.ДокСмета Get end)

                // *** End programmer edit section *** (ОтчОРасОсМат.ДокСмета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.ДокСмета Set start)

                // *** End programmer edit section *** (ОтчОРасОсМат.ДокСмета Set start)
                this.fДокСмета = value;
                // *** Start programmer edit section *** (ОтчОРасОсМат.ДокСмета Set end)

                // *** End programmer edit section *** (ОтчОРасОсМат.ДокСмета Set end)
            }
        }
        
        /// <summary>
        /// Отч о рас ос мат.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОРасОсМат.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (ОтчОРасОсМат.Номенклатура CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенклатура"})]
        [NotNull()]
        public virtual IIS.Proekt.Номенклатура Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.Номенклатура Get start)

                // *** End programmer edit section *** (ОтчОРасОсМат.Номенклатура Get start)
                IIS.Proekt.Номенклатура result = this.fНоменклатура;
                // *** Start programmer edit section *** (ОтчОРасОсМат.Номенклатура Get end)

                // *** End programmer edit section *** (ОтчОРасОсМат.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.Номенклатура Set start)

                // *** End programmer edit section *** (ОтчОРасОсМат.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (ОтчОРасОсМат.Номенклатура Set end)

                // *** End programmer edit section *** (ОтчОРасОсМат.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// Отч о рас ос мат.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОРасОсМат.РасхМатВСтро CustomAttributes)

        // *** End programmer edit section *** (ОтчОРасОсМат.РасхМатВСтро CustomAttributes)
        [PropertyStorage(new string[] {
                "РасхМатВСтро"})]
        [NotNull()]
        public virtual IIS.Proekt.РасхМатВСтро РасхМатВСтро
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.РасхМатВСтро Get start)

                // *** End programmer edit section *** (ОтчОРасОсМат.РасхМатВСтро Get start)
                IIS.Proekt.РасхМатВСтро result = this.fРасхМатВСтро;
                // *** Start programmer edit section *** (ОтчОРасОсМат.РасхМатВСтро Get end)

                // *** End programmer edit section *** (ОтчОРасОсМат.РасхМатВСтро Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.РасхМатВСтро Set start)

                // *** End programmer edit section *** (ОтчОРасОсМат.РасхМатВСтро Set start)
                this.fРасхМатВСтро = value;
                // *** Start programmer edit section *** (ОтчОРасОсМат.РасхМатВСтро Set end)

                // *** End programmer edit section *** (ОтчОРасОсМат.РасхМатВСтро Set end)
            }
        }
        
        /// <summary>
        /// Отч о рас ос мат.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОРасОсМат.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ОтчОРасОсМат.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Proekt.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.Сотрудники Get start)

                // *** End programmer edit section *** (ОтчОРасОсМат.Сотрудники Get start)
                IIS.Proekt.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ОтчОРасОсМат.Сотрудники Get end)

                // *** End programmer edit section *** (ОтчОРасОсМат.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОРасОсМат.Сотрудники Set start)

                // *** End programmer edit section *** (ОтчОРасОсМат.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ОтчОРасОсМат.Сотрудники Set end)

                // *** End programmer edit section *** (ОтчОРасОсМат.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчОРасОсМатE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчОРасОсМатE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчОРасОсМатE", typeof(IIS.Proekt.ОтчОРасОсМат));
                }
            }
            
            /// <summary>
            /// "ОтчОРасОсМатL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчОРасОсМатL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчОРасОсМатL", typeof(IIS.Proekt.ОтчОРасОсМат));
                }
            }
        }
    }
}
