//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расх мат в стро.
    /// </summary>
    // *** Start programmer edit section *** (РасхМатВСтро CustomAttributes)

    // *** End programmer edit section *** (РасхМатВСтро CustomAttributes)
    [AutoAltered()]
    [Caption("Расход материалов в строительстве")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасхМатВСтроE", new string[] {
            "КодСДР as \'Код СДР\'",
            "Объем as \'Объем\'",
            "Количество as \'Количество\'",
            "ЦенаЗаЕд as \'Цена за единицу\'",
            "СуммаИтого as \'Сумма итого\'"})]
    [View("РасхМатВСтроL", new string[] {
            "КодСДР as \'Код СДР\'",
            "Объем as \'Объем\'",
            "Количество as \'Количество\'",
            "ЦенаЗаЕд as \'Цена за единицу\'",
            "СуммаИтого as \'Сумма итого\'"})]
    public class РасхМатВСтро : ICSSoft.STORMNET.DataObject
    {
        
        private float fОбъем;
        
        private float fЦенаЗаЕд;
        
        private float fСуммаИтого;
        
        private float fКоличество;
        
        private int fКодСДР;
        
        // *** Start programmer edit section *** (РасхМатВСтро CustomMembers)

        // *** End programmer edit section *** (РасхМатВСтро CustomMembers)

        
        /// <summary>
        /// КодСДР.
        /// </summary>
        // *** Start programmer edit section *** (РасхМатВСтро.КодСДР CustomAttributes)

        // *** End programmer edit section *** (РасхМатВСтро.КодСДР CustomAttributes)
        public virtual int КодСДР
        {
            get
            {
                // *** Start programmer edit section *** (РасхМатВСтро.КодСДР Get start)

                // *** End programmer edit section *** (РасхМатВСтро.КодСДР Get start)
                int result = this.fКодСДР;
                // *** Start programmer edit section *** (РасхМатВСтро.КодСДР Get end)

                // *** End programmer edit section *** (РасхМатВСтро.КодСДР Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасхМатВСтро.КодСДР Set start)

                // *** End programmer edit section *** (РасхМатВСтро.КодСДР Set start)
                this.fКодСДР = value;
                // *** Start programmer edit section *** (РасхМатВСтро.КодСДР Set end)

                // *** End programmer edit section *** (РасхМатВСтро.КодСДР Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (РасхМатВСтро.Количество CustomAttributes)

        // *** End programmer edit section *** (РасхМатВСтро.Количество CustomAttributes)
        public virtual float Количество
        {
            get
            {
                // *** Start programmer edit section *** (РасхМатВСтро.Количество Get start)

                // *** End programmer edit section *** (РасхМатВСтро.Количество Get start)
                float result = this.fКоличество;
                // *** Start programmer edit section *** (РасхМатВСтро.Количество Get end)

                // *** End programmer edit section *** (РасхМатВСтро.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасхМатВСтро.Количество Set start)

                // *** End programmer edit section *** (РасхМатВСтро.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (РасхМатВСтро.Количество Set end)

                // *** End programmer edit section *** (РасхМатВСтро.Количество Set end)
            }
        }
        
        /// <summary>
        /// Объем.
        /// </summary>
        // *** Start programmer edit section *** (РасхМатВСтро.Объем CustomAttributes)

        // *** End programmer edit section *** (РасхМатВСтро.Объем CustomAttributes)
        public virtual float Объем
        {
            get
            {
                // *** Start programmer edit section *** (РасхМатВСтро.Объем Get start)

                // *** End programmer edit section *** (РасхМатВСтро.Объем Get start)
                float result = this.fОбъем;
                // *** Start programmer edit section *** (РасхМатВСтро.Объем Get end)

                // *** End programmer edit section *** (РасхМатВСтро.Объем Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасхМатВСтро.Объем Set start)

                // *** End programmer edit section *** (РасхМатВСтро.Объем Set start)
                this.fОбъем = value;
                // *** Start programmer edit section *** (РасхМатВСтро.Объем Set end)

                // *** End programmer edit section *** (РасхМатВСтро.Объем Set end)
            }
        }
        
        /// <summary>
        /// СуммаИтого.
        /// </summary>
        // *** Start programmer edit section *** (РасхМатВСтро.СуммаИтого CustomAttributes)

        // *** End programmer edit section *** (РасхМатВСтро.СуммаИтого CustomAttributes)
        public virtual float СуммаИтого
        {
            get
            {
                // *** Start programmer edit section *** (РасхМатВСтро.СуммаИтого Get start)

                // *** End programmer edit section *** (РасхМатВСтро.СуммаИтого Get start)
                float result = this.fСуммаИтого;
                // *** Start programmer edit section *** (РасхМатВСтро.СуммаИтого Get end)

                // *** End programmer edit section *** (РасхМатВСтро.СуммаИтого Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасхМатВСтро.СуммаИтого Set start)

                // *** End programmer edit section *** (РасхМатВСтро.СуммаИтого Set start)
                this.fСуммаИтого = value;
                // *** Start programmer edit section *** (РасхМатВСтро.СуммаИтого Set end)

                // *** End programmer edit section *** (РасхМатВСтро.СуммаИтого Set end)
            }
        }
        
        /// <summary>
        /// ЦенаЗаЕд.
        /// </summary>
        // *** Start programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд CustomAttributes)

        // *** End programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд CustomAttributes)
        public virtual float ЦенаЗаЕд
        {
            get
            {
                // *** Start programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд Get start)

                // *** End programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд Get start)
                float result = this.fЦенаЗаЕд;
                // *** Start programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд Get end)

                // *** End programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд Set start)

                // *** End programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд Set start)
                this.fЦенаЗаЕд = value;
                // *** Start programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд Set end)

                // *** End programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасхМатВСтроE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасхМатВСтроE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасхМатВСтроE", typeof(IIS.Proekt.РасхМатВСтро));
                }
            }
            
            /// <summary>
            /// "РасхМатВСтроL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасхМатВСтроL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасхМатВСтроL", typeof(IIS.Proekt.РасхМатВСтро));
                }
            }
        }
    }
}
