//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расх мат в стро.
    /// </summary>
    // *** Start programmer edit section *** (РасхМатВСтро CustomAttributes)

    // *** End programmer edit section *** (РасхМатВСтро CustomAttributes)
    [AutoAltered()]
    [Caption("Расход материалов в строительстве")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасхМатВСтроE", new string[] {
            "КодСДР as \'Код СДР\'",
            "Количество as \'Количество\'",
            "ЦенаЗаЕд as \'Цена за единицу\'",
            "СуммаИтого as \'Сумма итого\'",
            "ДокСмета as \'Объем работ по смете\'",
            "ДокСмета.ОбРабПоСмет as \'Объем работ по смете\'",
            "Номенклатура as \'Номенклатура\'",
            "Номенклатура.Наименов as \'Номенклатура\'",
            "ЕдИзмерен as \'Единицы измерения\'",
            "ЕдИзмерен.Наименование as \'Единицы измерения\'"})]
    [View("РасхМатВСтроL", new string[] {
            "КодСДР as \'Код СДР\'",
            "Количество as \'Количество\'",
            "ЦенаЗаЕд as \'Цена за единицу\'",
            "СуммаИтого as \'Сумма итого\'",
            "ДокСмета.ОбРабПоСмет as \'Объем работ по смете\'",
            "Номенклатура.Наименов as \'Номенклатура\'",
            "ЕдИзмерен.Наименование as \'Единицы измерения\'"})]
    public class РасхМатВСтро : ICSSoft.STORMNET.DataObject
    {
        
        private float fЦенаЗаЕд;
        
        private float fСуммаИтого;
        
        private float fКоличество;
        
        private int fКодСДР;
        
        private IIS.Proekt.Номенклатура fНоменклатура;
        
        private IIS.Proekt.ЕдИзмерен fЕдИзмерен;
        
        private IIS.Proekt.ДокСмета fДокСмета;
        
        // *** Start programmer edit section *** (РасхМатВСтро CustomMembers)

        // *** End programmer edit section *** (РасхМатВСтро CustomMembers)

        
        /// <summary>
        /// КодСДР.
        /// </summary>
        // *** Start programmer edit section *** (РасхМатВСтро.КодСДР CustomAttributes)

        // *** End programmer edit section *** (РасхМатВСтро.КодСДР CustomAttributes)
        public virtual int КодСДР
        {
            get
            {
                // *** Start programmer edit section *** (РасхМатВСтро.КодСДР Get start)

                // *** End programmer edit section *** (РасхМатВСтро.КодСДР Get start)
                int result = this.fКодСДР;
                // *** Start programmer edit section *** (РасхМатВСтро.КодСДР Get end)

                // *** End programmer edit section *** (РасхМатВСтро.КодСДР Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасхМатВСтро.КодСДР Set start)

                // *** End programmer edit section *** (РасхМатВСтро.КодСДР Set start)
                this.fКодСДР = value;
                // *** Start programmer edit section *** (РасхМатВСтро.КодСДР Set end)

                // *** End programmer edit section *** (РасхМатВСтро.КодСДР Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (РасхМатВСтро.Количество CustomAttributes)

        // *** End programmer edit section *** (РасхМатВСтро.Количество CustomAttributes)
        public virtual float Количество
        {
            get
            {
                // *** Start programmer edit section *** (РасхМатВСтро.Количество Get start)

                // *** End programmer edit section *** (РасхМатВСтро.Количество Get start)
                float result = this.fКоличество;
                // *** Start programmer edit section *** (РасхМатВСтро.Количество Get end)

                // *** End programmer edit section *** (РасхМатВСтро.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасхМатВСтро.Количество Set start)

                // *** End programmer edit section *** (РасхМатВСтро.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (РасхМатВСтро.Количество Set end)

                // *** End programmer edit section *** (РасхМатВСтро.Количество Set end)
            }
        }
        
        /// <summary>
        /// СуммаИтого.
        /// </summary>
        // *** Start programmer edit section *** (РасхМатВСтро.СуммаИтого CustomAttributes)

        // *** End programmer edit section *** (РасхМатВСтро.СуммаИтого CustomAttributes)
        public virtual float СуммаИтого
        {
            get
            {
                // *** Start programmer edit section *** (РасхМатВСтро.СуммаИтого Get start)

                // *** End programmer edit section *** (РасхМатВСтро.СуммаИтого Get start)
                float result = this.fСуммаИтого;
                // *** Start programmer edit section *** (РасхМатВСтро.СуммаИтого Get end)

                // *** End programmer edit section *** (РасхМатВСтро.СуммаИтого Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасхМатВСтро.СуммаИтого Set start)

                // *** End programmer edit section *** (РасхМатВСтро.СуммаИтого Set start)
                this.fСуммаИтого = value;
                // *** Start programmer edit section *** (РасхМатВСтро.СуммаИтого Set end)

                // *** End programmer edit section *** (РасхМатВСтро.СуммаИтого Set end)
            }
        }
        
        /// <summary>
        /// ЦенаЗаЕд.
        /// </summary>
        // *** Start programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд CustomAttributes)

        // *** End programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд CustomAttributes)
        public virtual float ЦенаЗаЕд
        {
            get
            {
                // *** Start programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд Get start)

                // *** End programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд Get start)
                float result = this.fЦенаЗаЕд;
                // *** Start programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд Get end)

                // *** End programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд Set start)

                // *** End programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд Set start)
                this.fЦенаЗаЕд = value;
                // *** Start programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд Set end)

                // *** End programmer edit section *** (РасхМатВСтро.ЦенаЗаЕд Set end)
            }
        }
        
        /// <summary>
        /// Расх мат в стро.
        /// </summary>
        // *** Start programmer edit section *** (РасхМатВСтро.ДокСмета CustomAttributes)

        // *** End programmer edit section *** (РасхМатВСтро.ДокСмета CustomAttributes)
        [PropertyStorage(new string[] {
                "ДокСмета"})]
        [NotNull()]
        public virtual IIS.Proekt.ДокСмета ДокСмета
        {
            get
            {
                // *** Start programmer edit section *** (РасхМатВСтро.ДокСмета Get start)

                // *** End programmer edit section *** (РасхМатВСтро.ДокСмета Get start)
                IIS.Proekt.ДокСмета result = this.fДокСмета;
                // *** Start programmer edit section *** (РасхМатВСтро.ДокСмета Get end)

                // *** End programmer edit section *** (РасхМатВСтро.ДокСмета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасхМатВСтро.ДокСмета Set start)

                // *** End programmer edit section *** (РасхМатВСтро.ДокСмета Set start)
                this.fДокСмета = value;
                // *** Start programmer edit section *** (РасхМатВСтро.ДокСмета Set end)

                // *** End programmer edit section *** (РасхМатВСтро.ДокСмета Set end)
            }
        }
        
        /// <summary>
        /// Расх мат в стро.
        /// </summary>
        // *** Start programmer edit section *** (РасхМатВСтро.ЕдИзмерен CustomAttributes)

        // *** End programmer edit section *** (РасхМатВСтро.ЕдИзмерен CustomAttributes)
        [PropertyStorage(new string[] {
                "ЕдИзмерен"})]
        [NotNull()]
        public virtual IIS.Proekt.ЕдИзмерен ЕдИзмерен
        {
            get
            {
                // *** Start programmer edit section *** (РасхМатВСтро.ЕдИзмерен Get start)

                // *** End programmer edit section *** (РасхМатВСтро.ЕдИзмерен Get start)
                IIS.Proekt.ЕдИзмерен result = this.fЕдИзмерен;
                // *** Start programmer edit section *** (РасхМатВСтро.ЕдИзмерен Get end)

                // *** End programmer edit section *** (РасхМатВСтро.ЕдИзмерен Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасхМатВСтро.ЕдИзмерен Set start)

                // *** End programmer edit section *** (РасхМатВСтро.ЕдИзмерен Set start)
                this.fЕдИзмерен = value;
                // *** Start programmer edit section *** (РасхМатВСтро.ЕдИзмерен Set end)

                // *** End programmer edit section *** (РасхМатВСтро.ЕдИзмерен Set end)
            }
        }
        
        /// <summary>
        /// Расх мат в стро.
        /// </summary>
        // *** Start programmer edit section *** (РасхМатВСтро.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (РасхМатВСтро.Номенклатура CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенклатура"})]
        [NotNull()]
        public virtual IIS.Proekt.Номенклатура Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (РасхМатВСтро.Номенклатура Get start)

                // *** End programmer edit section *** (РасхМатВСтро.Номенклатура Get start)
                IIS.Proekt.Номенклатура result = this.fНоменклатура;
                // *** Start programmer edit section *** (РасхМатВСтро.Номенклатура Get end)

                // *** End programmer edit section *** (РасхМатВСтро.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасхМатВСтро.Номенклатура Set start)

                // *** End programmer edit section *** (РасхМатВСтро.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (РасхМатВСтро.Номенклатура Set end)

                // *** End programmer edit section *** (РасхМатВСтро.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасхМатВСтроE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасхМатВСтроE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасхМатВСтроE", typeof(IIS.Proekt.РасхМатВСтро));
                }
            }
            
            /// <summary>
            /// "РасхМатВСтроL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасхМатВСтроL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасхМатВСтроL", typeof(IIS.Proekt.РасхМатВСтро));
                }
            }
        }
    }
}
