//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудники CustomAttributes)

    // *** End programmer edit section *** (Сотрудники CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДолжностьL", new string[] {
            "ТабелНомер as \'Табельный номер\'",
            "ФИО as \'ФИО\'",
            "СпраДолжнос.Наименование as \'Должность\'"})]
    [View("СотрудникиE", new string[] {
            "ТабелНомер as \'Табельный номер\'",
            "ФИО as \'ФИО\'",
            "СпраДолжнос as \'Должность\'",
            "СпраДолжнос.Наименование as \'Должность\'"})]
    [View("СотрудникиL", new string[] {
            "ТабелНомер as \'Табел номер\'",
            "ФИО as \'ФИО\'",
            "СпраДолжнос.Наименование as \'Наименование\'"})]
    public class Сотрудники : ICSSoft.STORMNET.DataObject
    {
        
        private int fТабелНомер;
        
        private string fФИО;
        
        private IIS.Proekt.СпраДолжнос fСпраДолжнос;
        
        // *** Start programmer edit section *** (Сотрудники CustomMembers)

        // *** End programmer edit section *** (Сотрудники CustomMembers)

        
        /// <summary>
        /// ТабелНомер.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ТабелНомер CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ТабелНомер CustomAttributes)
        public virtual int ТабелНомер
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ТабелНомер Get start)

                // *** End programmer edit section *** (Сотрудники.ТабелНомер Get start)
                int result = this.fТабелНомер;
                // *** Start programmer edit section *** (Сотрудники.ТабелНомер Get end)

                // *** End programmer edit section *** (Сотрудники.ТабелНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ТабелНомер Set start)

                // *** End programmer edit section *** (Сотрудники.ТабелНомер Set start)
                this.fТабелНомер = value;
                // *** Start programmer edit section *** (Сотрудники.ТабелНомер Set end)

                // *** End programmer edit section *** (Сотрудники.ТабелНомер Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ФИО CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ФИО Get start)

                // *** End programmer edit section *** (Сотрудники.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Сотрудники.ФИО Get end)

                // *** End programmer edit section *** (Сотрудники.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ФИО Set start)

                // *** End programmer edit section *** (Сотрудники.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Сотрудники.ФИО Set end)

                // *** End programmer edit section *** (Сотрудники.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.СпраДолжнос CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.СпраДолжнос CustomAttributes)
        [PropertyStorage(new string[] {
                "СпраДолжнос"})]
        [NotNull()]
        public virtual IIS.Proekt.СпраДолжнос СпраДолжнос
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.СпраДолжнос Get start)

                // *** End programmer edit section *** (Сотрудники.СпраДолжнос Get start)
                IIS.Proekt.СпраДолжнос result = this.fСпраДолжнос;
                // *** Start programmer edit section *** (Сотрудники.СпраДолжнос Get end)

                // *** End programmer edit section *** (Сотрудники.СпраДолжнос Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.СпраДолжнос Set start)

                // *** End programmer edit section *** (Сотрудники.СпраДолжнос Set start)
                this.fСпраДолжнос = value;
                // *** Start programmer edit section *** (Сотрудники.СпраДолжнос Set end)

                // *** End programmer edit section *** (Сотрудники.СпраДолжнос Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжностьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностьL", typeof(IIS.Proekt.Сотрудники));
                }
            }
            
            /// <summary>
            /// "СотрудникиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиE", typeof(IIS.Proekt.Сотрудники));
                }
            }
            
            /// <summary>
            /// "СотрудникиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиL", typeof(IIS.Proekt.Сотрудники));
                }
            }
        }
    }
}
