//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Спр контраг.
    /// </summary>
    // *** Start programmer edit section *** (СпрКонтраг CustomAttributes)

    // *** End programmer edit section *** (СпрКонтраг CustomAttributes)
    [PublishName("СправочникКонтрагенты")]
    [AutoAltered()]
    [Caption("Справочник контрагенты")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпрКонтрагE", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'",
            "ИНН as \'ИНН\'",
            "КПП as \'КПП\'",
            "ОГРН as \'ОГРН\'",
            "Телефон as \'Телефон\'"})]
    [View("СпрКонтрагL", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'",
            "ИНН as \'ИНН\'",
            "КПП as \'КПП\'",
            "ОГРН as \'ОГРН\'",
            "Телефон as \'Телефон\'"})]
    public class СпрКонтраг : ICSSoft.STORMNET.DataObject
    {
        
        private int fТелефон;
        
        private int fКПП;
        
        private int fКод;
        
        private int fОГРН;
        
        private string fНаименование;
        
        private int fИНН;
        
        // *** Start programmer edit section *** (СпрКонтраг CustomMembers)

        // *** End programmer edit section *** (СпрКонтраг CustomMembers)

        
        /// <summary>
        /// ИНН.
        /// </summary>
        // *** Start programmer edit section *** (СпрКонтраг.ИНН CustomAttributes)

        // *** End programmer edit section *** (СпрКонтраг.ИНН CustomAttributes)
        public virtual int ИНН
        {
            get
            {
                // *** Start programmer edit section *** (СпрКонтраг.ИНН Get start)

                // *** End programmer edit section *** (СпрКонтраг.ИНН Get start)
                int result = this.fИНН;
                // *** Start programmer edit section *** (СпрКонтраг.ИНН Get end)

                // *** End programmer edit section *** (СпрКонтраг.ИНН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрКонтраг.ИНН Set start)

                // *** End programmer edit section *** (СпрКонтраг.ИНН Set start)
                this.fИНН = value;
                // *** Start programmer edit section *** (СпрКонтраг.ИНН Set end)

                // *** End programmer edit section *** (СпрКонтраг.ИНН Set end)
            }
        }
        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (СпрКонтраг.Код CustomAttributes)

        // *** End programmer edit section *** (СпрКонтраг.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (СпрКонтраг.Код Get start)

                // *** End programmer edit section *** (СпрКонтраг.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (СпрКонтраг.Код Get end)

                // *** End programmer edit section *** (СпрКонтраг.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрКонтраг.Код Set start)

                // *** End programmer edit section *** (СпрКонтраг.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (СпрКонтраг.Код Set end)

                // *** End programmer edit section *** (СпрКонтраг.Код Set end)
            }
        }
        
        /// <summary>
        /// КПП.
        /// </summary>
        // *** Start programmer edit section *** (СпрКонтраг.КПП CustomAttributes)

        // *** End programmer edit section *** (СпрКонтраг.КПП CustomAttributes)
        public virtual int КПП
        {
            get
            {
                // *** Start programmer edit section *** (СпрКонтраг.КПП Get start)

                // *** End programmer edit section *** (СпрКонтраг.КПП Get start)
                int result = this.fКПП;
                // *** Start programmer edit section *** (СпрКонтраг.КПП Get end)

                // *** End programmer edit section *** (СпрКонтраг.КПП Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрКонтраг.КПП Set start)

                // *** End programmer edit section *** (СпрКонтраг.КПП Set start)
                this.fКПП = value;
                // *** Start programmer edit section *** (СпрКонтраг.КПП Set end)

                // *** End programmer edit section *** (СпрКонтраг.КПП Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СпрКонтраг.Наименование CustomAttributes)

        // *** End programmer edit section *** (СпрКонтраг.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СпрКонтраг.Наименование Get start)

                // *** End programmer edit section *** (СпрКонтраг.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СпрКонтраг.Наименование Get end)

                // *** End programmer edit section *** (СпрКонтраг.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрКонтраг.Наименование Set start)

                // *** End programmer edit section *** (СпрКонтраг.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СпрКонтраг.Наименование Set end)

                // *** End programmer edit section *** (СпрКонтраг.Наименование Set end)
            }
        }
        
        /// <summary>
        /// ОГРН.
        /// </summary>
        // *** Start programmer edit section *** (СпрКонтраг.ОГРН CustomAttributes)

        // *** End programmer edit section *** (СпрКонтраг.ОГРН CustomAttributes)
        public virtual int ОГРН
        {
            get
            {
                // *** Start programmer edit section *** (СпрКонтраг.ОГРН Get start)

                // *** End programmer edit section *** (СпрКонтраг.ОГРН Get start)
                int result = this.fОГРН;
                // *** Start programmer edit section *** (СпрКонтраг.ОГРН Get end)

                // *** End programmer edit section *** (СпрКонтраг.ОГРН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрКонтраг.ОГРН Set start)

                // *** End programmer edit section *** (СпрКонтраг.ОГРН Set start)
                this.fОГРН = value;
                // *** Start programmer edit section *** (СпрКонтраг.ОГРН Set end)

                // *** End programmer edit section *** (СпрКонтраг.ОГРН Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (СпрКонтраг.Телефон CustomAttributes)

        // *** End programmer edit section *** (СпрКонтраг.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (СпрКонтраг.Телефон Get start)

                // *** End programmer edit section *** (СпрКонтраг.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (СпрКонтраг.Телефон Get end)

                // *** End programmer edit section *** (СпрКонтраг.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрКонтраг.Телефон Set start)

                // *** End programmer edit section *** (СпрКонтраг.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (СпрКонтраг.Телефон Set end)

                // *** End programmer edit section *** (СпрКонтраг.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпрКонтрагE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрКонтрагE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрКонтрагE", typeof(IIS.Proekt.СпрКонтраг));
                }
            }
            
            /// <summary>
            /// "СпрКонтрагL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрКонтрагL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрКонтрагL", typeof(IIS.Proekt.СпрКонтраг));
                }
            }
        }
    }
}
