//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Спра должнос.
    /// </summary>
    // *** Start programmer edit section *** (СпраДолжнос CustomAttributes)

    // *** End programmer edit section *** (СпраДолжнос CustomAttributes)
    [AutoAltered()]
    [Caption("Справочник должности")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпраДолжносE", new string[] {
            "КодДолжности as \'Код должности\'",
            "Наименование as \'Наименование\'"})]
    [View("СпраДолжносL", new string[] {
            "КодДолжности as \'Код должности\'",
            "Наименование as \'Наименование\'"})]
    public class СпраДолжнос : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private int fКодДолжности;
        
        // *** Start programmer edit section *** (СпраДолжнос CustomMembers)

        // *** End programmer edit section *** (СпраДолжнос CustomMembers)

        
        /// <summary>
        /// КодДолжности.
        /// </summary>
        // *** Start programmer edit section *** (СпраДолжнос.КодДолжности CustomAttributes)

        // *** End programmer edit section *** (СпраДолжнос.КодДолжности CustomAttributes)
        public virtual int КодДолжности
        {
            get
            {
                // *** Start programmer edit section *** (СпраДолжнос.КодДолжности Get start)

                // *** End programmer edit section *** (СпраДолжнос.КодДолжности Get start)
                int result = this.fКодДолжности;
                // *** Start programmer edit section *** (СпраДолжнос.КодДолжности Get end)

                // *** End programmer edit section *** (СпраДолжнос.КодДолжности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпраДолжнос.КодДолжности Set start)

                // *** End programmer edit section *** (СпраДолжнос.КодДолжности Set start)
                this.fКодДолжности = value;
                // *** Start programmer edit section *** (СпраДолжнос.КодДолжности Set end)

                // *** End programmer edit section *** (СпраДолжнос.КодДолжности Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СпраДолжнос.Наименование CustomAttributes)

        // *** End programmer edit section *** (СпраДолжнос.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СпраДолжнос.Наименование Get start)

                // *** End programmer edit section *** (СпраДолжнос.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СпраДолжнос.Наименование Get end)

                // *** End programmer edit section *** (СпраДолжнос.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпраДолжнос.Наименование Set start)

                // *** End programmer edit section *** (СпраДолжнос.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СпраДолжнос.Наименование Set end)

                // *** End programmer edit section *** (СпраДолжнос.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпраДолжносE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпраДолжносE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпраДолжносE", typeof(IIS.Proekt.СпраДолжнос));
                }
            }
            
            /// <summary>
            /// "СпраДолжносL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпраДолжносL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпраДолжносL", typeof(IIS.Proekt.СпраДолжнос));
                }
            }
        }
    }
}
