//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч смета.
    /// </summary>
    // *** Start programmer edit section *** (ТЧСмета CustomAttributes)

    // *** End programmer edit section *** (ТЧСмета CustomAttributes)
    [AutoAltered()]
    [Caption("Табличная часть сметы")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧСметаE", new string[] {
            "СтоимСтроРаб as \'Стоимость строительных работ\'",
            "СтоимМонРаб as \'Стоимость монтажных работ\'",
            "СтоимОборуд as \'Стоимость оборудования\'"})]
    [View("ТЧСметаL", new string[] {
            "СтоимСтроРаб as \'Стоимость строительных работ\'",
            "СтоимМонРаб as \'Стоимость монтажных работ\'",
            "СтоимОборуд as \'Стоимость оборудования\'"})]
    public class ТЧСмета : ICSSoft.STORMNET.DataObject
    {
        
        private float fСтоимСтроРаб;
        
        private float fСтоимОборуд;
        
        private float fСтоимМонРаб;
        
        private IIS.Proekt.ДокСмета fДокСмета;
        
        // *** Start programmer edit section *** (ТЧСмета CustomMembers)

        // *** End programmer edit section *** (ТЧСмета CustomMembers)

        
        /// <summary>
        /// СтоимМонРаб.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСмета.СтоимМонРаб CustomAttributes)

        // *** End programmer edit section *** (ТЧСмета.СтоимМонРаб CustomAttributes)
        public virtual float СтоимМонРаб
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСмета.СтоимМонРаб Get start)

                // *** End programmer edit section *** (ТЧСмета.СтоимМонРаб Get start)
                float result = this.fСтоимМонРаб;
                // *** Start programmer edit section *** (ТЧСмета.СтоимМонРаб Get end)

                // *** End programmer edit section *** (ТЧСмета.СтоимМонРаб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСмета.СтоимМонРаб Set start)

                // *** End programmer edit section *** (ТЧСмета.СтоимМонРаб Set start)
                this.fСтоимМонРаб = value;
                // *** Start programmer edit section *** (ТЧСмета.СтоимМонРаб Set end)

                // *** End programmer edit section *** (ТЧСмета.СтоимМонРаб Set end)
            }
        }
        
        /// <summary>
        /// СтоимОборуд.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСмета.СтоимОборуд CustomAttributes)

        // *** End programmer edit section *** (ТЧСмета.СтоимОборуд CustomAttributes)
        public virtual float СтоимОборуд
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСмета.СтоимОборуд Get start)

                // *** End programmer edit section *** (ТЧСмета.СтоимОборуд Get start)
                float result = this.fСтоимОборуд;
                // *** Start programmer edit section *** (ТЧСмета.СтоимОборуд Get end)

                // *** End programmer edit section *** (ТЧСмета.СтоимОборуд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСмета.СтоимОборуд Set start)

                // *** End programmer edit section *** (ТЧСмета.СтоимОборуд Set start)
                this.fСтоимОборуд = value;
                // *** Start programmer edit section *** (ТЧСмета.СтоимОборуд Set end)

                // *** End programmer edit section *** (ТЧСмета.СтоимОборуд Set end)
            }
        }
        
        /// <summary>
        /// СтоимСтроРаб.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСмета.СтоимСтроРаб CustomAttributes)

        // *** End programmer edit section *** (ТЧСмета.СтоимСтроРаб CustomAttributes)
        public virtual float СтоимСтроРаб
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСмета.СтоимСтроРаб Get start)

                // *** End programmer edit section *** (ТЧСмета.СтоимСтроРаб Get start)
                float result = this.fСтоимСтроРаб;
                // *** Start programmer edit section *** (ТЧСмета.СтоимСтроРаб Get end)

                // *** End programmer edit section *** (ТЧСмета.СтоимСтроРаб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСмета.СтоимСтроРаб Set start)

                // *** End programmer edit section *** (ТЧСмета.СтоимСтроРаб Set start)
                this.fСтоимСтроРаб = value;
                // *** Start programmer edit section *** (ТЧСмета.СтоимСтроРаб Set end)

                // *** End programmer edit section *** (ТЧСмета.СтоимСтроРаб Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Proekt.ДокСмета.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСмета.ДокСмета CustomAttributes)

        // *** End programmer edit section *** (ТЧСмета.ДокСмета CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ДокСмета"})]
        public virtual IIS.Proekt.ДокСмета ДокСмета
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСмета.ДокСмета Get start)

                // *** End programmer edit section *** (ТЧСмета.ДокСмета Get start)
                IIS.Proekt.ДокСмета result = this.fДокСмета;
                // *** Start programmer edit section *** (ТЧСмета.ДокСмета Get end)

                // *** End programmer edit section *** (ТЧСмета.ДокСмета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСмета.ДокСмета Set start)

                // *** End programmer edit section *** (ТЧСмета.ДокСмета Set start)
                this.fДокСмета = value;
                // *** Start programmer edit section *** (ТЧСмета.ДокСмета Set end)

                // *** End programmer edit section *** (ТЧСмета.ДокСмета Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧСметаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧСметаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧСметаE", typeof(IIS.Proekt.ТЧСмета));
                }
            }
            
            /// <summary>
            /// "ТЧСметаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧСметаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧСметаL", typeof(IIS.Proekt.ТЧСмета));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧСмета.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧСмета CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧСмета CustomAttributes)
    public class DetailArrayOfТЧСмета : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Proekt.DetailArrayOfТЧСмета members)

        // *** End programmer edit section *** (IIS.Proekt.DetailArrayOfТЧСмета members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧСмета by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧСмета.
        /// </summary>
        public DetailArrayOfТЧСмета(IIS.Proekt.ДокСмета fДокСмета) : 
                base(typeof(ТЧСмета), ((ICSSoft.STORMNET.DataObject)(fДокСмета)))
        {
        }
        
        public IIS.Proekt.ТЧСмета this[int index]
        {
            get
            {
                return ((IIS.Proekt.ТЧСмета)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Proekt.ТЧСмета dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
