//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч смета.
    /// </summary>
    // *** Start programmer edit section *** (ТЧСмета CustomAttributes)

    // *** End programmer edit section *** (ТЧСмета CustomAttributes)
    [AutoAltered()]
    [Caption("Табличная часть сметы")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧСметаE", new string[] {
            "СтоимСтроРаб as \'Стоимость строительных работ\'",
            "СтоимМонРаб as \'Стоимость монтажных работ\'",
            "СтоимОборуд as \'Стоимость оборудования\'"})]
    [View("ТЧСметаL", new string[] {
            "СтоимСтроРаб as \'Стоимость строительных работ\'",
            "СтоимМонРаб as \'Стоимость монтажных работ\'",
            "СтоимОборуд as \'Стоимость оборудования\'"})]
    public class ТЧСмета : ICSSoft.STORMNET.DataObject
    {
        
        private float fСтоимСтроРаб;
        
        private float fСтоимОборуд;
        
        private float fСтоимМонРаб;
        
        // *** Start programmer edit section *** (ТЧСмета CustomMembers)

        // *** End programmer edit section *** (ТЧСмета CustomMembers)

        
        /// <summary>
        /// СтоимМонРаб.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСмета.СтоимМонРаб CustomAttributes)

        // *** End programmer edit section *** (ТЧСмета.СтоимМонРаб CustomAttributes)
        public virtual float СтоимМонРаб
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСмета.СтоимМонРаб Get start)

                // *** End programmer edit section *** (ТЧСмета.СтоимМонРаб Get start)
                float result = this.fСтоимМонРаб;
                // *** Start programmer edit section *** (ТЧСмета.СтоимМонРаб Get end)

                // *** End programmer edit section *** (ТЧСмета.СтоимМонРаб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСмета.СтоимМонРаб Set start)

                // *** End programmer edit section *** (ТЧСмета.СтоимМонРаб Set start)
                this.fСтоимМонРаб = value;
                // *** Start programmer edit section *** (ТЧСмета.СтоимМонРаб Set end)

                // *** End programmer edit section *** (ТЧСмета.СтоимМонРаб Set end)
            }
        }
        
        /// <summary>
        /// СтоимОборуд.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСмета.СтоимОборуд CustomAttributes)

        // *** End programmer edit section *** (ТЧСмета.СтоимОборуд CustomAttributes)
        public virtual float СтоимОборуд
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСмета.СтоимОборуд Get start)

                // *** End programmer edit section *** (ТЧСмета.СтоимОборуд Get start)
                float result = this.fСтоимОборуд;
                // *** Start programmer edit section *** (ТЧСмета.СтоимОборуд Get end)

                // *** End programmer edit section *** (ТЧСмета.СтоимОборуд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСмета.СтоимОборуд Set start)

                // *** End programmer edit section *** (ТЧСмета.СтоимОборуд Set start)
                this.fСтоимОборуд = value;
                // *** Start programmer edit section *** (ТЧСмета.СтоимОборуд Set end)

                // *** End programmer edit section *** (ТЧСмета.СтоимОборуд Set end)
            }
        }
        
        /// <summary>
        /// СтоимСтроРаб.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСмета.СтоимСтроРаб CustomAttributes)

        // *** End programmer edit section *** (ТЧСмета.СтоимСтроРаб CustomAttributes)
        public virtual float СтоимСтроРаб
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСмета.СтоимСтроРаб Get start)

                // *** End programmer edit section *** (ТЧСмета.СтоимСтроРаб Get start)
                float result = this.fСтоимСтроРаб;
                // *** Start programmer edit section *** (ТЧСмета.СтоимСтроРаб Get end)

                // *** End programmer edit section *** (ТЧСмета.СтоимСтроРаб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСмета.СтоимСтроРаб Set start)

                // *** End programmer edit section *** (ТЧСмета.СтоимСтроРаб Set start)
                this.fСтоимСтроРаб = value;
                // *** Start programmer edit section *** (ТЧСмета.СтоимСтроРаб Set end)

                // *** End programmer edit section *** (ТЧСмета.СтоимСтроРаб Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧСметаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧСметаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧСметаE", typeof(IIS.Proekt.ТЧСмета));
                }
            }
            
            /// <summary>
            /// "ТЧСметаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧСметаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧСметаL", typeof(IIS.Proekt.ТЧСмета));
                }
            }
        }
    }
}
